// ============================================
// PROJECT OMNI: STABILITY ENGINE
// Mathematical model for computing system stability
// ============================================

import { SystemType, LifeSystem, SystemAttribute } from './core.schema';

// Re-export for convenience
export type { SystemType } from './core.schema';

// ============================================
// ATTRIBUTE EFFECT TYPES
// ============================================

/**
 * Effect type determines the mathematical relationship
 */
export type EffectType =
    | 'linear'       // value * coefficient
    | 'exponential'  // value^exponent * coefficient
    | 'threshold'    // value > threshold ? highValue : lowValue
    | 'inverse'      // coefficient / value
    | 'logarithmic'  // log(value) * coefficient
    | 'custom';      // user-defined expression

/**
 * Defines how an attribute affects stability
 */
export interface AttributeEffect {
    /** Unique effect ID */
    id: string;

    /** ID of the attribute this applies to */
    attributeId: string;

    /** Type of mathematical relationship */
    effectType: EffectType;

    /** Direction of effect on stability */
    direction: 'positive' | 'negative';

    /** Main coefficient/weight */
    coefficient: number;

    /** For threshold type: the trigger value */
    threshold?: number;

    /** For threshold type: value above threshold */
    highValue?: number;

    /** For threshold type: value below threshold */
    lowValue?: number;

    /** For exponential type: the exponent */
    exponent?: number;

    /** For custom type: JavaScript expression */
    customExpression?: string;

    /** Human-readable description */
    description?: string;
}

/**
 * A rule that modifies stability based on conditions
 */
export interface StabilityRule {
    /** Unique rule ID */
    id: string;

    /** Rule name */
    name: string;

    /** Condition expression (JS-like) */
    condition: string;

    /** Action when condition is true */
    action: RuleAction;

    /** Priority (higher = evaluated first) */
    priority: number;

    /** Is rule active? */
    isActive: boolean;

    /** Generated by LLM survey? */
    isLLMGenerated?: boolean;
}

/**
 * Action to take when rule condition is met
 */
export interface RuleAction {
    type: 'modify_stability' | 'add_alert' | 'trigger_notification' | 'chain_rule';

    /** For modify_stability: amount to add/subtract */
    stabilityDelta?: number;

    /** For add_alert: alert message */
    alertMessage?: string;

    /** For add_alert: severity level */
    alertSeverity?: 'info' | 'warning' | 'critical';

    /** For chain_rule: ID of next rule to evaluate */
    chainRuleId?: string;
}

/**
 * Complete system model configuration
 */
export interface SystemModel {
    /** System this model belongs to */
    systemId: SystemType;

    /** Base stability score (before effects) */
    baseStability: number;

    /** Attribute effects */
    effects: AttributeEffect[];

    /** Stability rules */
    rules: StabilityRule[];

    /** Minimum stability floor */
    minStability: number;

    /** Maximum stability ceiling */
    maxStability: number;
}

// ============================================
// DEFAULT SYSTEM MODELS
// ============================================

export const DEFAULT_SYSTEM_MODELS: Record<SystemType, SystemModel> = {
    health: {
        systemId: 'health',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'health_energy',
                attributeId: 'energy',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.3,
                description: 'Higher energy improves stability'
            },
            {
                id: 'health_sleep',
                attributeId: 'sleep_quality',
                effectType: 'threshold',
                direction: 'positive',
                coefficient: 1,
                threshold: 60,
                highValue: 20,
                lowValue: -10,
                description: 'Good sleep (>60%) adds stability, poor sleep reduces it'
            },
            {
                id: 'health_stress',
                attributeId: 'stress',
                effectType: 'exponential',
                direction: 'negative',
                coefficient: 0.5,
                exponent: 1.2,
                description: 'Stress has compounding negative effect'
            }
        ],
        rules: [
            {
                id: 'health_burnout',
                name: 'Burnout Warning',
                condition: 'stress > 80 && energy < 30',
                action: {
                    type: 'add_alert',
                    alertMessage: 'Burnout risk detected - consider rest',
                    alertSeverity: 'critical'
                },
                priority: 10,
                isActive: true
            }
        ]
    },
    career: {
        systemId: 'career',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'career_productivity',
                attributeId: 'productivity',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.4,
                description: 'Productivity directly improves career stability'
            },
            {
                id: 'career_skill_growth',
                attributeId: 'skill_growth',
                effectType: 'logarithmic',
                direction: 'positive',
                coefficient: 15,
                description: 'Skill growth has diminishing returns'
            }
        ],
        rules: []
    },
    finance: {
        systemId: 'finance',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'finance_runway',
                attributeId: 'runway',
                effectType: 'threshold',
                direction: 'positive',
                coefficient: 1,
                threshold: 6,
                highValue: 30,
                lowValue: -20,
                description: '6+ months runway is healthy, less is risky'
            },
            {
                id: 'finance_savings_rate',
                attributeId: 'savings_rate',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.3,
                description: 'Higher savings rate improves stability'
            }
        ],
        rules: [
            {
                id: 'finance_low_runway',
                name: 'Low Runway Alert',
                condition: 'runway < 3',
                action: {
                    type: 'add_alert',
                    alertMessage: 'Financial runway below 3 months',
                    alertSeverity: 'warning'
                },
                priority: 10,
                isActive: true
            }
        ]
    },
    mind: {
        systemId: 'mind',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'mind_clarity',
                attributeId: 'clarity',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.35,
                description: 'Mental clarity improves stability'
            },
            {
                id: 'mind_creativity',
                attributeId: 'creativity',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.25,
                description: 'Creativity contributes to mental wellbeing'
            }
        ],
        rules: []
    },
    relationships: {
        systemId: 'relationships',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'rel_connection',
                attributeId: 'connection',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.4,
                description: 'Connection quality directly improves stability'
            },
            {
                id: 'rel_network',
                attributeId: 'network_health',
                effectType: 'logarithmic',
                direction: 'positive',
                coefficient: 12,
                description: 'Network health with diminishing returns'
            },
            {
                id: 'rel_isolation',
                attributeId: 'isolation_level',
                effectType: 'exponential',
                direction: 'negative',
                coefficient: 0.8,
                exponent: 1.3,
                description: 'Isolation has compounding negative effect'
            }
        ],
        rules: [
            {
                id: 'rel_isolation_warning',
                name: 'Isolation Warning',
                condition: 'isolation_level > 70',
                action: {
                    type: 'add_alert',
                    alertMessage: 'High isolation detected - reach out to someone',
                    alertSeverity: 'warning'
                },
                priority: 10,
                isActive: true
            }
        ]
    },
    environment: {
        systemId: 'environment',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'env_organization',
                attributeId: 'organization',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.3,
                description: 'Organization improves stability'
            },
            {
                id: 'env_comfort',
                attributeId: 'comfort',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.25,
                description: 'Comfort contributes to environmental stability'
            }
        ],
        rules: []
    },
    time: {
        systemId: 'time',
        baseStability: 50,
        minStability: 0,
        maxStability: 100,
        effects: [
            {
                id: 'time_focus',
                attributeId: 'focus_time',
                effectType: 'threshold',
                direction: 'positive',
                coefficient: 1,
                threshold: 20,
                highValue: 25,
                lowValue: -15,
                description: '20+ hours focus time is healthy'
            },
            {
                id: 'time_balance',
                attributeId: 'balance',
                effectType: 'linear',
                direction: 'positive',
                coefficient: 0.4,
                description: 'Work-life balance improves stability'
            }
        ],
        rules: [
            {
                id: 'time_overwork',
                name: 'Overwork Warning',
                condition: 'focus_time > 50 && balance < 30',
                action: {
                    type: 'add_alert',
                    alertMessage: 'Overwork detected - balance may suffer',
                    alertSeverity: 'warning'
                },
                priority: 10,
                isActive: true
            }
        ]
    }
};

// ============================================
// STABILITY ENGINE
// ============================================

export interface StabilityResult {
    score: number;
    breakdown: EffectBreakdown[];
    triggeredRules: TriggeredRule[];
    alerts: Alert[];
}

export interface EffectBreakdown {
    effectId: string;
    attributeId: string;
    attributeValue: number;
    contribution: number;
    description?: string;
}

export interface TriggeredRule {
    ruleId: string;
    ruleName: string;
    action: RuleAction;
}

export interface Alert {
    message: string;
    severity: 'info' | 'warning' | 'critical';
    ruleId: string;
}

/**
 * Computes stability score from attributes and model
 */
export function computeStability(
    attributes: SystemAttribute[],
    model: SystemModel
): StabilityResult {
    const breakdown: EffectBreakdown[] = [];
    const triggeredRules: TriggeredRule[] = [];
    const alerts: Alert[] = [];

    let score = model.baseStability;

    // Create attribute lookup map
    const attrMap = new Map(attributes.map(a => [a.id, a.value]));

    // Apply each effect
    for (const effect of model.effects) {
        const attrValue = attrMap.get(effect.attributeId);
        if (attrValue === undefined) continue;

        let contribution = calculateEffect(attrValue, effect);

        // Apply direction
        if (effect.direction === 'negative') {
            contribution = -contribution;
        }

        score += contribution;

        breakdown.push({
            effectId: effect.id,
            attributeId: effect.attributeId,
            attributeValue: attrValue,
            contribution,
            description: effect.description
        });
    }

    // Evaluate rules
    for (const rule of model.rules.filter(r => r.isActive).sort((a, b) => b.priority - a.priority)) {
        if (evaluateCondition(rule.condition, attrMap)) {
            triggeredRules.push({
                ruleId: rule.id,
                ruleName: rule.name,
                action: rule.action
            });

            // Apply action
            if (rule.action.type === 'modify_stability' && rule.action.stabilityDelta) {
                score += rule.action.stabilityDelta;
            }

            if (rule.action.type === 'add_alert' && rule.action.alertMessage) {
                alerts.push({
                    message: rule.action.alertMessage,
                    severity: rule.action.alertSeverity || 'info',
                    ruleId: rule.id
                });
            }
        }
    }

    // Clamp to bounds
    score = Math.max(model.minStability, Math.min(model.maxStability, score));

    return { score, breakdown, triggeredRules, alerts };
}

/**
 * Calculate the numeric effect contribution
 */
function calculateEffect(value: number, effect: AttributeEffect): number {
    switch (effect.effectType) {
        case 'linear':
            return value * effect.coefficient;

        case 'exponential':
            return Math.pow(value / 100, effect.exponent || 2) * 100 * effect.coefficient;

        case 'threshold':
            return value > (effect.threshold || 50)
                ? (effect.highValue || 10)
                : (effect.lowValue || 0);

        case 'inverse':
            return value > 0 ? (effect.coefficient / value) * 100 : 0;

        case 'logarithmic':
            return value > 0 ? Math.log(value + 1) * effect.coefficient : 0;

        case 'custom':
            if (effect.customExpression) {
                try {
                    // Safe evaluation with limited scope
                    const fn = new Function('value', `return ${effect.customExpression}`);
                    return fn(value) * effect.coefficient;
                } catch {
                    return 0;
                }
            }
            return 0;

        default:
            return 0;
    }
}

/**
 * Evaluate a condition expression against attributes
 */
function evaluateCondition(condition: string, attrMap: Map<string, number>): boolean {
    try {
        // Build variable context
        const context: Record<string, number> = {};
        for (const [id, value] of attrMap) {
            // Convert attribute IDs to valid JS identifiers
            const varName = id.replace(/[^a-zA-Z0-9_]/g, '_');
            context[varName] = value;
        }

        // Create function with context
        const varNames = Object.keys(context);
        const varValues = Object.values(context);
        const fn = new Function(...varNames, `return ${condition}`);

        return Boolean(fn(...varValues));
    } catch {
        console.warn(`Failed to evaluate condition: ${condition}`);
        return false;
    }
}

// ============================================
// SURVEY QUESTIONS
// ============================================

export interface SurveyQuestion {
    id: string;
    systemId: SystemType;
    attributeId: string;
    question: string;
    options: SurveyOption[];
}

export interface SurveyOption {
    label: string;
    value: number;
    effectModifier?: Partial<AttributeEffect>;
}

/**
 * Hard-coded survey questions for each system
 */
export const SYSTEM_SURVEY: SurveyQuestion[] = [
    // Health System
    {
        id: 'health_sleep_sensitivity',
        systemId: 'health',
        attributeId: 'sleep_quality',
        question: 'How does poor sleep affect your next day?',
        options: [
            { label: 'Barely noticeable', value: 1, effectModifier: { coefficient: 0.1 } },
            { label: 'Mildly affected', value: 2, effectModifier: { coefficient: 0.3 } },
            { label: 'Significantly impaired', value: 3, effectModifier: { coefficient: 0.5 } },
            { label: 'Completely unable to function', value: 4, effectModifier: { coefficient: 0.8 } }
        ]
    },
    {
        id: 'health_stress_pattern',
        systemId: 'health',
        attributeId: 'stress',
        question: 'How does stress accumulate for you?',
        options: [
            { label: 'It dissipates quickly', value: 1, effectModifier: { effectType: 'linear', coefficient: 0.2 } },
            { label: 'It builds gradually', value: 2, effectModifier: { effectType: 'linear', coefficient: 0.4 } },
            { label: 'It compounds exponentially', value: 3, effectModifier: { effectType: 'exponential', exponent: 1.3 } },
            { label: 'It hits a threshold then crashes', value: 4, effectModifier: { effectType: 'threshold', threshold: 70 } }
        ]
    },

    // Relationships System
    {
        id: 'rel_isolation_impact',
        systemId: 'relationships',
        attributeId: 'isolation_level',
        question: 'How does isolation affect your wellbeing?',
        options: [
            { label: 'I recharge when alone', value: 1, effectModifier: { direction: 'positive', coefficient: 0.2 } },
            { label: 'Neutral - neither helps nor hurts', value: 2, effectModifier: { coefficient: 0 } },
            { label: 'Extended isolation drains me', value: 3, effectModifier: { direction: 'negative', coefficient: 0.4 } },
            { label: 'Isolation severely impacts my mental health', value: 4, effectModifier: { direction: 'negative', coefficient: 0.8, effectType: 'exponential' } }
        ]
    },
    {
        id: 'rel_connection_need',
        systemId: 'relationships',
        attributeId: 'connection',
        question: 'How often do you need meaningful connection?',
        options: [
            { label: 'Rarely - once a month is fine', value: 1, effectModifier: { coefficient: 0.2 } },
            { label: 'Weekly connection is ideal', value: 2, effectModifier: { coefficient: 0.3 } },
            { label: 'Several times a week', value: 3, effectModifier: { coefficient: 0.5 } },
            { label: 'Daily connection is essential', value: 4, effectModifier: { coefficient: 0.7 } }
        ]
    },

    // Time System
    {
        id: 'time_focus_threshold',
        systemId: 'time',
        attributeId: 'focus_time',
        question: 'How many hours of deep focus do you need weekly?',
        options: [
            { label: '10-15 hours', value: 1, effectModifier: { threshold: 10 } },
            { label: '20-25 hours', value: 2, effectModifier: { threshold: 20 } },
            { label: '30-35 hours', value: 3, effectModifier: { threshold: 30 } },
            { label: '40+ hours', value: 4, effectModifier: { threshold: 40 } }
        ]
    },
    {
        id: 'time_balance_sensitivity',
        systemId: 'time',
        attributeId: 'balance',
        question: 'How sensitive are you to work-life imbalance?',
        options: [
            { label: 'Can work intensely for long periods', value: 1, effectModifier: { coefficient: 0.2 } },
            { label: 'Need moderate balance', value: 2, effectModifier: { coefficient: 0.4 } },
            { label: 'Balance is important to me', value: 3, effectModifier: { coefficient: 0.6 } },
            { label: 'Balance is critical - imbalance affects everything', value: 4, effectModifier: { coefficient: 0.8 } }
        ]
    },

    // Finance System
    {
        id: 'finance_runway_comfort',
        systemId: 'finance',
        attributeId: 'runway',
        question: 'How much financial runway do you need to feel secure?',
        options: [
            { label: '1-3 months', value: 1, effectModifier: { threshold: 1 } },
            { label: '3-6 months', value: 2, effectModifier: { threshold: 3 } },
            { label: '6-12 months', value: 3, effectModifier: { threshold: 6 } },
            { label: '12+ months', value: 4, effectModifier: { threshold: 12 } }
        ]
    },

    // Mind System
    {
        id: 'mind_clarity_importance',
        systemId: 'mind',
        attributeId: 'clarity',
        question: 'How important is mental clarity to your daily function?',
        options: [
            { label: 'Can operate on autopilot', value: 1, effectModifier: { coefficient: 0.2 } },
            { label: 'Prefer clarity but can manage', value: 2, effectModifier: { coefficient: 0.35 } },
            { label: 'Clarity significantly affects output', value: 3, effectModifier: { coefficient: 0.5 } },
            { label: 'Mental fog severely impairs me', value: 4, effectModifier: { coefficient: 0.7 } }
        ]
    }
];

export type SurveyResponses = Record<string, number>;
